### ISSUE TITLE
Seemingly not working anymore "Cannot read property '1' of null"

### ISSUE THREAD

**Issue by Sponxie** [addshore/browser-facebook-advert-interest-cleaner#10]
Not working

**Comment by addshore** [comment]
Thanks for the report.
I'm guessing Facebook changed something once again, I'll take a look.

What language were you using?

**Comment by Sponxie** [comment]
en_US

**Comment by addshore** [comment]
I just took a look and it seems to be working for me for en_US on https://www.facebook.com/adpreferences/ad_settings when navigating to the 2 pages where it should appear.

If you still can't get it to work then a screenshot would be appreciated, and checking in the dev console to see if there are any errors etc.

**Comment by psitem** [comment]
v1.1.0, Chrome v90.0.4430.93, en_US, [screenshot](https://imgur.com/2me2DD8). 

Nothing in the console after the initial pageload.

**Comment by addshore** [comment]
Thanks for the report, I'll try to take another look!

**Comment by addshore** [comment]
I can confirm that this is not working for me.

Looks like it is an issue detecting the language of the page, facebook must have changed something.

```
Uncaught TypeError: Cannot read property '1' of null
    at Object.detectLanguageCode (adpreferences-ad_settings-categories-other.js:232)
    at Object../scripts/adpreferences-ad_settings-categories-other.js (adpreferences-ad_settings-categories-other.js:106)
    at __webpack_require__ (adpreferences-ad_settings-categories-other.js:20)
    at adpreferences-ad_settings-categories-other.js:84
    at adpreferences-ad_settings-categories-other.js:87
```

let me take a look!

**Comment by addshore** [comment]
When you're next update happens to 1.1.1 this should be working again.
