### ISSUE TITLE
Doesn't work for me on macOS - tried both, Chrome & Firefox

### ISSUE THREAD

**Issue by sush4nt77** [addshore/browser-facebook-advert-interest-cleaner#14]
<img width="1440" alt="Screenshot 2021-05-18 at 11 52 52 PM" src="https://user-images.githubusercontent.com/17920957/118703862-2ac07c00-b834-11eb-9161-476c00f65b83.png">

URL: https://www.facebook.com/adpreferences/ad_settings
Language: en_US

**Comment by addshore** [comment]
I can confirm it is not working today, I expect this is the same as https://github.com/addshore/browser-facebook-advert-interest-cleaner/issues/10 so watch there for a fix!
